// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	users "homework10/internal/users"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, ad
func (_m *Repository) AddUser(ctx context.Context, ad *users.User) (int64, error) {
	ret := _m.Called(ctx, ad)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.User) (int64, error)); ok {
		return rf(ctx, ad)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *users.User) int64); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *users.User) error); ok {
		r1 = rf(ctx, ad)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, ID
func (_m *Repository) DeleteUser(ctx context.Context, ID int64) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserByID provides a mock function with given fields: ctx, ID
func (_m *Repository) UserByID(ctx context.Context, ID int64) (*users.User, error) {
	ret := _m.Called(ctx, ID)

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*users.User, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *users.User); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
