// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	ads "homework10/internal/ads"

	context "context"

	mock "github.com/stretchr/testify/mock"

	users "homework10/internal/users"
)

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// AdByID provides a mock function with given fields: ctx, ID
func (_m *App) AdByID(ctx context.Context, ID int64) (*ads.Ad, error) {
	ret := _m.Called(ctx, ID)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*ads.Ad, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *ads.Ad); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdsByPattern provides a mock function with given fields: ctx, p
func (_m *App) AdsByPattern(ctx context.Context, p *ads.Pattern) ([]*ads.Ad, error) {
	ret := _m.Called(ctx, p)

	var r0 []*ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ads.Pattern) ([]*ads.Ad, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ads.Pattern) []*ads.Ad); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ads.Pattern) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeAdStatus provides a mock function with given fields: ctx, ID, userID, published
func (_m *App) ChangeAdStatus(ctx context.Context, ID int64, userID int64, published bool) (*ads.Ad, error) {
	ret := _m.Called(ctx, ID, userID, published)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) (*ads.Ad, error)); ok {
		return rf(ctx, ID, userID, published)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) *ads.Ad); ok {
		r0 = rf(ctx, ID, userID, published)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, bool) error); ok {
		r1 = rf(ctx, ID, userID, published)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAd provides a mock function with given fields: ctx, title, text, userID
func (_m *App) CreateAd(ctx context.Context, title string, text string, userID int64) (*ads.Ad, error) {
	ret := _m.Called(ctx, title, text, userID)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (*ads.Ad, error)); ok {
		return rf(ctx, title, text, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) *ads.Ad); ok {
		r0 = rf(ctx, title, text, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, title, text, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, nick, email
func (_m *App) CreateUser(ctx context.Context, nick string, email string) (*users.User, error) {
	ret := _m.Called(ctx, nick, email)

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*users.User, error)); ok {
		return rf(ctx, nick, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *users.User); ok {
		r0 = rf(ctx, nick, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, nick, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAd provides a mock function with given fields: ctx, ID, userID
func (_m *App) DeleteAd(ctx context.Context, ID int64, userID int64) (*ads.Ad, error) {
	ret := _m.Called(ctx, ID, userID)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*ads.Ad, error)); ok {
		return rf(ctx, ID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *ads.Ad); ok {
		r0 = rf(ctx, ID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, ID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, ID
func (_m *App) DeleteUser(ctx context.Context, ID int64) (*users.User, error) {
	ret := _m.Called(ctx, ID)

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*users.User, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *users.User); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAd provides a mock function with given fields: ctx, ID, userID, title, text
func (_m *App) UpdateAd(ctx context.Context, ID int64, userID int64, title string, text string) (*ads.Ad, error) {
	ret := _m.Called(ctx, ID, userID, title, text)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) (*ads.Ad, error)); ok {
		return rf(ctx, ID, userID, title, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) *ads.Ad); ok {
		r0 = rf(ctx, ID, userID, title, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string) error); ok {
		r1 = rf(ctx, ID, userID, title, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, ID, nick, email
func (_m *App) UpdateUser(ctx context.Context, ID int64, nick string, email string) (*users.User, error) {
	ret := _m.Called(ctx, ID, nick, email)

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (*users.User, error)); ok {
		return rf(ctx, ID, nick, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) *users.User); ok {
		r0 = rf(ctx, ID, nick, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, ID, nick, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserByID provides a mock function with given fields: ctx, ID
func (_m *App) UserByID(ctx context.Context, ID int64) (*users.User, error) {
	ret := _m.Called(ctx, ID)

	var r0 *users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*users.User, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *users.User); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewApp interface {
	mock.TestingT
	Cleanup(func())
}

// NewApp creates a new instance of App. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApp(t mockConstructorTestingTNewApp) *App {
	mock := &App{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
